[book]
authors = ["John Telford"]
language = "en"
multilingual = false
src = "src"
title = "Cloudflare Plan"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["././mdbook-admonish.css"]
